collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.6756272
color:
  saturation: 0.9623656
  brandStrength: 0.3351254
  lightness: 0.8584229
  brandColors:
    - '#161211'
    - '#787167'
    - '#FFFFFA'
    - '#C9CBC6'
    - '#BD562B'
  rhythmicContrast: 0.7741935
layout_spectrum: 0.5723943593911827
name: Osbornetest
