collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9623656
  brandStrength: 0.9157706
  lightness: 0.8584229
  brandColors:
    - '#161211'
    - '#787167'
    - '#FFFFFA'
    - '#C9CBC6'
    - '#BD562B'
  rhythmicContrast: 0.7741935
typography_spectrum: 0.6756272
layout_spectrum: 0.9569892
name: Osbornetest
